name: workshop_shelf_helper
description: "Application for managing electronic components inventory."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.0  
  path_provider: ^2.1.1  
  path: ^1.8.3  
  pdf: ^3.10.7  
  csv: ^6.0.0  
  intl: ^0.19.0
  collection: ^1.19.1  
  diacritic: ^0.1.5
  file_picker: ^8.1.4
  desktop_drop: ^0.4.4
  dio: ^5.4.0
  url_launcher: ^6.2.0
  package_info_plus: ^9.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env

